version: '3'

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    image: nextcloud:apache
    restart: unless-stopped
    container_name: nextcloud
    expose:
      - "80"
    volumes:
      - ./nextcloud:/var/www/html:z
      - /media/nextcloud/data:/var/www/html/data
    environment:
      - "MYSQL_HOST=db"
      - "REDIS_HOST=redis"
      - "VIRTUAL_HOST=nextcloud.zairecloud.pt"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=nextcloud.zairecloud.pt"
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - nginx-proxy_network
      - default

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

networks:
  nginx-proxy_network:
    external: true